/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportfoundRouteImport } from './routes/reportfound'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyItemsRouteImport } from './routes/my-items'
import { Route as MyClaimsRouteImport } from './routes/my-claims'
import { Route as HerobannerRouteImport } from './routes/herobanner'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as AdminReportItemRouteImport } from './routes/admin/report-item'

const ReportfoundRoute = ReportfoundRouteImport.update({
  id: '/reportfound',
  path: '/reportfound',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyItemsRoute = MyItemsRouteImport.update({
  id: '/my-items',
  path: '/my-items',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClaimsRoute = MyClaimsRouteImport.update({
  id: '/my-claims',
  path: '/my-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const HerobannerRoute = HerobannerRouteImport.update({
  id: '/herobanner',
  path: '/herobanner',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportItemRoute = AdminReportItemRouteImport.update({
  id: '/admin/report-item',
  path: '/admin/report-item',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/herobanner': typeof HerobannerRoute
  '/my-claims': typeof MyClaimsRoute
  '/my-items': typeof MyItemsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/reportfound': typeof ReportfoundRoute
  '/admin/report-item': typeof AdminReportItemRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/herobanner': typeof HerobannerRoute
  '/my-claims': typeof MyClaimsRoute
  '/my-items': typeof MyItemsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/reportfound': typeof ReportfoundRoute
  '/admin/report-item': typeof AdminReportItemRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/herobanner': typeof HerobannerRoute
  '/my-claims': typeof MyClaimsRoute
  '/my-items': typeof MyItemsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/reportfound': typeof ReportfoundRoute
  '/admin/report-item': typeof AdminReportItemRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/help'
    | '/herobanner'
    | '/my-claims'
    | '/my-items'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/report'
    | '/reportfound'
    | '/admin/report-item'
    | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/help'
    | '/herobanner'
    | '/my-claims'
    | '/my-items'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/report'
    | '/reportfound'
    | '/admin/report-item'
    | '/item/$id'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/dashboard'
    | '/help'
    | '/herobanner'
    | '/my-claims'
    | '/my-items'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/report'
    | '/reportfound'
    | '/admin/report-item'
    | '/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  HerobannerRoute: typeof HerobannerRoute
  MyClaimsRoute: typeof MyClaimsRoute
  MyItemsRoute: typeof MyItemsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  ReportfoundRoute: typeof ReportfoundRoute
  AdminReportItemRoute: typeof AdminReportItemRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportfound': {
      id: '/reportfound'
      path: '/reportfound'
      fullPath: '/reportfound'
      preLoaderRoute: typeof ReportfoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-items': {
      id: '/my-items'
      path: '/my-items'
      fullPath: '/my-items'
      preLoaderRoute: typeof MyItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-claims': {
      id: '/my-claims'
      path: '/my-claims'
      fullPath: '/my-claims'
      preLoaderRoute: typeof MyClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herobanner': {
      id: '/herobanner'
      path: '/herobanner'
      fullPath: '/herobanner'
      preLoaderRoute: typeof HerobannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/report-item': {
      id: '/admin/report-item'
      path: '/admin/report-item'
      fullPath: '/admin/report-item'
      preLoaderRoute: typeof AdminReportItemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  HerobannerRoute: HerobannerRoute,
  MyClaimsRoute: MyClaimsRoute,
  MyItemsRoute: MyItemsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  ReportfoundRoute: ReportfoundRoute,
  AdminReportItemRoute: AdminReportItemRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
