/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportfoundRouteImport } from './routes/reportfound'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyItemsRouteImport } from './routes/my-items'
import { Route as MyClaimsRouteImport } from './routes/my-claims'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'

const ReportfoundRoute = ReportfoundRouteImport.update({
  id: '/reportfound',
  path: '/reportfound',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyItemsRoute = MyItemsRouteImport.update({
  id: '/my-items',
  path: '/my-items',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClaimsRoute = MyClaimsRouteImport.update({
  id: '/my-claims',
  path: '/my-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/help': typeof HelpRoute
  '/my-claims': typeof MyClaimsRoute
  '/my-items': typeof MyItemsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/reportfound': typeof ReportfoundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/help': typeof HelpRoute
  '/my-claims': typeof MyClaimsRoute
  '/my-items': typeof MyItemsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/reportfound': typeof ReportfoundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/help': typeof HelpRoute
  '/my-claims': typeof MyClaimsRoute
  '/my-items': typeof MyItemsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/reportfound': typeof ReportfoundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/help'
    | '/my-claims'
    | '/my-items'
    | '/notifications'
    | '/profile'
    | '/report'
    | '/reportfound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/help'
    | '/my-claims'
    | '/my-items'
    | '/notifications'
    | '/profile'
    | '/report'
    | '/reportfound'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/help'
    | '/my-claims'
    | '/my-items'
    | '/notifications'
    | '/profile'
    | '/report'
    | '/reportfound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  HelpRoute: typeof HelpRoute
  MyClaimsRoute: typeof MyClaimsRoute
  MyItemsRoute: typeof MyItemsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  ReportfoundRoute: typeof ReportfoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportfound': {
      id: '/reportfound'
      path: '/reportfound'
      fullPath: '/reportfound'
      preLoaderRoute: typeof ReportfoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-items': {
      id: '/my-items'
      path: '/my-items'
      fullPath: '/my-items'
      preLoaderRoute: typeof MyItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-claims': {
      id: '/my-claims'
      path: '/my-claims'
      fullPath: '/my-claims'
      preLoaderRoute: typeof MyClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  HelpRoute: HelpRoute,
  MyClaimsRoute: MyClaimsRoute,
  MyItemsRoute: MyItemsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  ReportfoundRoute: ReportfoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
